name: flutter_blue_plus_darwin
description: iOS and macOS implementation of the flutter_blue_plus plugin.
version: 1.33.0
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blue_plus_platform_interface:
    path: ../flutter_blue_plus_platform_interface

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      ios:
        pluginClass: FlutterBluePlusPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterBluePlusPlugin
        sharedDarwinSource: true
