name: flutter_blue_plus
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 1.33.0
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_android: ^1.33.0
  flutter_blue_plus_darwin: ^1.33.0
  flutter_blue_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blue_plus_android:
    path: ../flutter_blue_plus_android
  flutter_blue_plus_darwin:
    path: ../flutter_blue_plus_darwin
  flutter_blue_plus_platform_interface:
    path: ../flutter_blue_plus_platform_interface

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_plus_android
      ios:
        default_package: flutter_blue_plus_darwin
      macos:
        default_package: flutter_blue_plus_darwin
