name: flutter_blue_plus_android
description: Android implementation of the flutter_blue_plus plugin.
version: 1.33.0
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blue_plus_platform_interface:
    path: ../flutter_blue_plus_platform_interface

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      android:
        package: com.lib.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
